[package]
name = "legalmoves_benchmark"
version = "0.1.0"
authors = ["jinpu"]

[dependencies]
[dependencies.usiagent]
#git = "https://github.com/j6k1/USIAgent.git"
path = "F:\\source\\Rust\\USIAgent"

